### ISSUE TITLE
Which Map?

### ISSUE THREAD

**Issue by milovanderlinden** [mmdolbow/geohipster-sightings#3]
![image](https://user-images.githubusercontent.com/106038/64922994-b10dfa80-d7d5-11e9-8c3a-a534829d2e79.png)

or

![image](https://user-images.githubusercontent.com/106038/64923006-d00c8c80-d7d5-11e9-9aaa-433e6ca89761.png)

**Comment by milovanderlinden** [comment]
Or maybe even better; a mixture of both?
![image](https://user-images.githubusercontent.com/106038/64926122-04923f80-d7fa-11e9-8bad-2a294c99f50b.png)

**Comment by milovanderlinden** [comment]
Because true GeoHipsters need to show of their cartographic skills ;-)

**Comment by mmdolbow** [comment]
Honestly Milo, all three of these look **terrific!**  I don't really love the second one but it IS bold. If you can't decide, go with the mixture one, it's pretty awesome.

**Comment by milovanderlinden** [comment]
Thanks for the compliment. I like option 3 too although I think it would be good to turn the vector layer invisible when zooming in.

**Comment by milovanderlinden** [comment]
By the way terrific translates to horrible in dutch, is that what you mean?

**Comment by mmdolbow** [comment]
The vector layer is the country summary? If so, I agree, set a scale
dependency so it is off when zoomed in.

Sorry for the translation, I definitely did NOT mean "horrible"! :-) They
look great!
