### ISSUE TITLE
No iframe needed`

### ISSUE THREAD

**Issue by milovanderlinden** [mmdolbow/geohipster-sightings#4]
The current map on the website is a Google Map in an IFrame. When you embed the JavaScript and the CSS, an IFrame is no longer necessary.

**Comment by mmdolbow** [comment]
Yes, in the new website, if we're able to embed JS and CSS, we'll skip the iFrame. It's not a requirement to make it work within an iFrame. Worst case if we can't embed via the Wordpress tools, we'll host on gh-pages.

**Comment by milovanderlinden** [comment]
It should be pretty straight forward to pull in the js and css, you can even put the local parts inline and use the other dependencies via CDN.

**Comment by mmdolbow** [comment]
Wordpress won't let us embed the JS without an upgrade, but that's OK - we'll just host with GH pages.
